id = "k8s-context-server-dev"
name = "K8s context server development"
version = "0.0.1"
schema_version = 1
authors = ["Your Name <you@example.com>"]
description = "My cool extension"
repository = "https://github.com/your-name/my-zed-extension"

[context_servers.k8s-mcp-context-server-dev]
name = "K8S Context Server Development"
